# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
    -   id: black

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.5
    hooks:
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.0
    hooks:
    -   id: mypy
        # The mypy hook runs in its own environment, so we need to install
        # the same dependencies as the project to allow it to type check them.
        additional_dependencies: [
            "pandas", "numpy", "scikit-learn", "flask", "tensorflow", "keras",
            "langchain", "openai", "pydantic", "requests", "sqlalchemy",
            "types-python-dateutil", "types-pytz", "types-requests",
            "types-PyYAML", "sqlalchemy-stubs"
        ]
