name: 'Setup Python Environment'
description: 'Sets up Python, installs Poetry, and caches/installs dependencies.'

runs:
  using: "composite"
  steps:
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'poetry'

    - name: Install Poetry
      shell: bash
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        export PATH="$HOME/.local/bin:$PATH"
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        poetry --version
        poetry install --no-interaction
