name: 'Setup Python Environment'
description: 'Sets up Python, installs Poetry, and caches/installs dependencies.'

runs:
  using: "composite"
  steps:
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Poetry and dependencies
      shell: bash
      run: |
        set -eux
        POETRY_HOME=".poetry"
        mkdir -p "$POETRY_HOME"
        curl -sSL https://install.python-poetry.org | python3 - --install-dir "$POETRY_HOME" --version 1.8.3
        echo "$POETRY_HOME/bin" >> $GITHUB_PATH
        poetry --version
        poetry install --no-interaction --no-ansi
