name: PR Checks

on:
  pull_request:
    branches:
      - main

jobs:
  pre-commit-check:
    name: Pre-commit check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # checkout repo code to virtual machine

      - name: Run Pre-commit Checks
        # This path points to the local action we just created
        uses: ./.github/actions/run-pre-commit



# add step to check for permissions key
# add step to run unit tests
