name: PR Checks

on:
  pull_request:
    branches:
      - main

jobs:
  pre-commit-check:
    name: Pre-commit check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # checkout repo code to virtual machine

      - name: Setup Environment and Install Dependencies
        uses:  ./.github/actions/run-pre-commit

  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: pre-commit-check
    steps:
      - uses: actions/checkout@v4

      - name: "Set up Python 3.12"
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'


      - name: "Install poetry environment"
        shell: bash
        run: |
          pip install "poetry==2.2.1"
          poetry install --all-groups

      - name: Run tests with pytest
        run: poetry run pytest
        env:
          QDRANT_API_KEY: "test-key"
          GOOGLE_API_KEY: "test-key"
